server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://124.221.166.184:3306/zhuque_v2?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: wake
    password: wake12345
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      connection-timeout: 30000
      max-lifetime: 600000
      idle-timeout: 180000
      connection-test-query: SELECT 1
      keepalive-time: 30000
      validation-timeout: 5000

  # Redis 配置
  data:
    redis:
      host: 124.221.166.184
      port: 6379
      password: zwk_azul
      database: 1
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 20
          max-wait: -1ms
          max-idle: 10
          min-idle: 5

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    "[wake.su.zhuque]": DEBUG
