<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
         http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>wake.su</groupId>
        <artifactId>zhuque-backend</artifactId>
        <version>2.0.0</version>
    </parent>

    <artifactId>web-admin</artifactId>
    <name>管理后台Web模块</name>
    <description>管理后台启动模块</description>

    <dependencies>
        <!-- 公共模块 -->
        <dependency>
            <groupId>wake.su</groupId>
            <artifactId>zhuque-common</artifactId>
        </dependency>

        <!-- 模型模块 -->
        <dependency>
            <groupId>wake.su</groupId>
            <artifactId>zhuque-model</artifactId>
        </dependency>

        <!-- 服务模块 -->
        <dependency>
            <groupId>wake.su</groupId>
            <artifactId>zhuque-service</artifactId>
        </dependency>

        <!-- Spring Boot Starter -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
        </dependency>

        <!-- Spring Boot Actuator -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>

        <!-- Lombok -->
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <mainClass>wake.su.zhuque.WebAdminApplication</mainClass>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
