spring:
  application:
    name: zhuque-admin

  profiles:
    active: dev

  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: INFO
    ai.houyi.zhuque: DEBUG
